strict: true

included:
  - macos/Sources/NoicanMenuBar

line_length:
  warning: 140
  error: 180
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - id
    - uid

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

reporter: xcode
